import Head from 'next/head';
import styles from '../styles/Portfolio.module.scss';
import { useSelector } from 'react-redux';

import NavigationMenu from '../components/NavigationMenu';
import ThemeMenu from '../components/theme/ThemeMenu';

const Portfolio = () => {
	const state = useSelector((state) => state);
	const {
		colorPrimary,
		colorSecondary,
		colorTertiary,
		backgroundPrimary,
		backgroundSecondary,
	} = state.theme;

	const { canvas, splash, title, line } = styles;

	const style = {
		color: colorPrimary,
		backgroundColor: colorSecondary,
	};

	return (
		<div className={canvas} style={style}>
			<Head>
				<title>Louis Whisenant</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<NavigationMenu />
			<ThemeMenu />

			<div
				className={splash}
				style={{ backgroundColor: backgroundPrimary }}>
				<h1 className={title} style={{ color: colorTertiary }}>
					Louis Whisenant
				</h1>
				<hr className={line} />
				<h2 className={title} style={{ color: colorTertiary }}>
					Web Developer
				</h2>

				<div>{colorPrimary}</div>
				<div>{colorSecondary}</div>
				<div>{colorTertiary}</div>
			</div>
		</div>
	);
};

const mapStateToProps = (state) => ({});

export default Portfolio;
